<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0-android</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>

		<CheckEolTargetFramework>false</CheckEolTargetFramework>

		<MauiVersion>8.0.100</MauiVersion>
		<OutputType>Exe</OutputType>
		<RootNamespace>restaurant</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ApplicationTitle>SIMR Admin</ApplicationTitle>
		<ApplicationId>com.simr.admin</ApplicationId>
		<ApplicationDisplayVersion>2.0</ApplicationDisplayVersion>
		<ApplicationVersion>2</ApplicationVersion>
		<AssemblyName>SIMRAdmin</AssemblyName>
		<AssemblyTitle>SIMR Admin</AssemblyTitle>
		<AssemblyProduct>SIMR Admin</AssemblyProduct>
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">23.0</SupportedOSPlatformVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>

		<DefaultLanguage>en</DefaultLanguage>
	</PropertyGroup>

	<ItemGroup>
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" />
		<MauiImage Include="Resources\Images\*" />
		<MauiFont Include="Resources\Fonts\*" />
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <AndroidResource Remove="Platforms\Android\Resources\values\strings.xml" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="google-services.json" />
		<None Remove="Platforms\Android\google-services.json" />
		<None Remove="setup_script.iss" />
		<None Remove="welcome_image.bmp" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="CommunityToolkit.Maui" Version="7.0.1" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.0" />
		<PackageReference Include="FirebaseAdmin" Version="3.4.0" />
		<PackageReference Include="FirebaseAuthentication.net" Version="4.1.0" />
		<PackageReference Include="FirebaseDatabase.net" Version="5.0.0" />
		<PackageReference Include="Google.Cloud.Firestore" Version="3.11.0" />
		<PackageReference Include="LiveCharts.Core" Version="0.9.8" />
		<PackageReference Include="Microcharts.Maui" Version="1.0.1" />

		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.100" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.100" />

		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />

		<PackageReference Include="Plugin.Firebase.CloudMessaging" Version="3.1.2" />

		<PackageReference Include="Plugin.Firebase.Core" Version="3.1.1" />

		<PackageReference Include="Plugin.FirebasePushNotification" Version="3.4.35" />
		<PackageReference Include="SendGrid" Version="9.29.3" />

		<PackageReference Include="SkiaSharp" Version="2.88.9" />
		<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="2.88.9" />

		<PackageReference Include="System.Private.Uri" Version="4.3.2" />
		<PackageReference Include="Twilio" Version="7.13.4" />

	</ItemGroup>

	<ItemGroup>
		<Compile Update="Dashboard.xaml.cs">
			<DependentUpon>Dashboard.xaml</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Resources\Images\" />
	</ItemGroup>

	<ItemGroup>
	  <GoogleServicesJson Include="google-services.json" />
	  <GoogleServicesJson Include="Platforms\Android\google-services.json" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="CameraGandaci.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>